services:
  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"

  rayping:
    build: .
    container_name: rayping
    depends_on:
      - redis
    ports:
      - "8080:8080"
    environment:
      SERVER_PORT: 8080
      REDIS_ADDR: redis:6379
      REDIS_PASSWORD: ""
      REDIS_DB: 0
      LOG_LEVEL: debug
    volumes:
      - ./keys/github_deploy_key:/app/keys/github_deploy_key:ro
    command: ["api"]
